build_hmgapi:
  image: mcr.microsoft.com/dotnet/sdk
  stage: build
  script:
    - cd HmgAPI
    - dotnet build -c Release
    - dotnet publish -c Release -o bin/Release/net/publish
  # Archive the published artifacts to be passed to downstream jobs
  artifacts:
    paths:
      - HmgAPI/bin/Release/netcoreapp3.1/publish
      - HmgAPI/bin/Release/net/publish

build_consoledebugger:
  image: mcr.microsoft.com/dotnet/sdk
  stage: build
  script:
    - cd ConsoleDebugger
    - dotnet build -c Release
    - dotnet publish -c Release -o bin/Release/net/publish
  artifacts:
    paths:
      - ConsoleDebugger/bin/Release/netcoreapp3.1/publish
      - ConsoleDebugger/bin/Release/net/publish

set_version:
  stage: build
  script:
    - chmod +x ./SetVersion.sh
    - VERSION="$(./SetVersion.sh)"
    - echo "Set version to $VERSION"
  only:
    - main

build_image:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t "${DOCKER_REPO}:latest" .
    - docker tag "${DOCKER_REPO}:latest" "${DOCKER_REPO}:${CI_COMMIT_SHORT_SHA}"
    - docker tag "${DOCKER_REPO}:latest" "${DOCKER_REPO}:${VERSION}"
    - echo "Pushing Docker image..."
    - docker push "${DOCKER_REPO}:latest"
    - docker push "${DOCKER_REPO}:${CI_COMMIT_SHORT_SHA}"
    - docker push "${DOCKER_REPO}:${VERSION}"
  only:
    - main
  except:
    - schedules
  // Error handling to retry failed stages up to 3 times, with a 10-second delay between retries, and allow the stage to be interrupted if necessary.
  retry:
    max: 3
    when: always
    delay: 10
    untracked: true
  interruptible: true