clean_images:
  image: docker:latest
  stage: cleaN
  services:
    - docker:dind
  script:
    - IMAGE_TAG=$(date --date="${CI_COMMIT_TIMESTAMP}" "+%Y.%m.%d.%H%M")-${CI_COMMIT_SHORT_SHA}-latest
    - docker image rm "${DOCKER_REPO}:${IMAGE_TAG}"
  only:
    - main
  when: always
  allow_failure: true
