image: mcr.microsoft.com/dotnet/core/sdk:2.1

stages:
  - build
  - test
  - scan
  - publish
  - staging
  - prod
  - cleanup

include:
  - local: build.yml
  - local: test.yml
  - local: scan.yml
  - local: publish.yml
  - local: staging.yml
  - local: prod.yml
  - local: clean.yml