publish_image_docker:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_ENDPOINT_URL
  script:
    - IMAGE_TAG=$(date --date="${CI_COMMIT_TIMESTAMP}" "+%Y.%m.%d.%H%M")-${CI_COMMIT_SHORT_SHA}-latest
    - docker push $DOCKER_REPO:$IMAGE_TAG
  only:
    - main
